### ISSUE TITLE
Should there be method AbstractQueryBuilderFilterImposer::join() ?

### ISSUE THREAD

**Issue by krzysztof-gzocha** [krzysztof-gzocha/searcher#10]
Method `join()` in class `AbstractQueryBuilderFilterImposer` is checking if there already is such join in passed (as a parameter) QueryBuilder and if it is, it will do nothing - in other case it will create new join.
Is it correct way? Is there better way/implementation to check it?

**Situation**
Two different FilterImposers are adding conditions to entity that is accessible via some relationship, so it needs to perform JOIN operation. If both would just do joining with the same alias, then Doctrine would throw an exception because there already is such join. In case both of them would just do the join with different (unique) alias, then we would have two different joins which is a mistake, right?

**Example**
Searching for entity `Person` that lives in some country for longer than some period. There is entity `Address`. There is one-to-many relationship between `Person` and `Address`.
Code in `CountryFilterImposer`:
```
$queryBuilder->join('p.adresses', 'address')->andWhere(/** some condition */);
```
Code in `TimePeriodFilterImposer`:
```
$queryBuilder->join('p.adresses', 'address')->andWhere(/** some condition */);
```
Both needs to call `join()` somehow, because they are not aware of each other and can be called separately.

**Workaround**
Create all possible joins in QueryBuilder before passing it to SearchingContext

**Comment by alanbem** [comment]
Propel did it nicely with its `active queries`

```php
BookQuery::create()
  ->withAuthor()
  ->filterByTitle('Pride & Prejudice')
  ->findOne();
```

...so I propose `with` instead of `join`. `JOIN` is very SQL-like and I assume this library can/will work with non-SQL storages?

**Comment by alanbem** [comment]
Oh, I see - you are working on Doctrine query builder directly. 
I would create some kind of abstraction over query builder, than thing like multiple join could be resolved within this abstraction and not within imposers.
Also switching to new storages would be easier as only your query builder would have to be replaced not imposers.

**Comment by krzysztof-gzocha** [comment]
Additional abstraction which will cover building queries for at least Doctrine, Propel and Elastica?
It doesn't seem like a simplest solution to me :P

**Comment by alanbem** [comment]
Well, its only way IMHO to make it clean - otherwise every imposer will have to check if JOIN is already defined within query builder (I remember it's not very easy to do) to prevent multiple joins.

**Comment by krzysztof-gzocha** [comment]
Some basic implementation is already there - but it can be better of course.

And what do you think about skipping this problem by forcing user to do all the joins before passing QueryBuilder to searcher?
