### ISSUE TITLE
Integration with external libs should probably sit in external repositories.

### ISSUE THREAD

**Issue by XanderEmu** [krzysztof-gzocha/searcher#16]
If I understood it properly this library is supposed to be datasource agnostic - it can work with Doctrine ORM but it might also work with Elasticsearch if you provide an appropriate adapter. Yet in this repository we can find files like `searcher/src/KGzocha/Searcher/FilterImposer/AbstractQueryBuilderFilterImposer.php` with direct dependency on Doctrine ORM.

You could solve it the way Gaufrette team did it. You keep only interfaces/abstracts here and create separate repositories with Doctrine ORM implementation, Doctrine ODM implementation, Elastic Search implementation and so on. Your composer file can suggest those dependencies without requiring those.

**Comment by krzysztof-gzocha** [comment]
You are right. That's why I've put Doctrine ORM to suggest in composer.json. As you can see there is only "php" in requirements - nothing else. You can use this library without Doctrine. If you would like to add FilterImposer for ElasticSearch then we will do the same: put it into suggest, require-dev and thats it. 

What's wrong with this approach?

**Comment by XanderEmu** [comment]
That's not exactly what I meant.

Class `AbstractQueryBuilderFilterImposer` will be of no use for someone who's using elastic search. It's one class for now but in future there will be something like e.g. `AbstractElasticSearchQueryBuilderFilterImposer` which sits there only for elastic search, maybe other classes to be used with other data sources/libraries. Those classes could sit in separate repositories.

By the way - `AbstractQueryBuilderFilterImposer` could have "Doctrine" somewhere in it's name ;]

**Comment by krzysztof-gzocha** [comment]
Look [here](https://github.com/KnpLabs/Gaufrette/blob/master/composer.json). Gaufrette solves this problem in exact the same way as I do. In other point of view: if there would be separate repository for this connection then how big would it be? Just one file? Just one class? It does not look right for me.
I was talking about it couple days ago with @drgomesp, maybe he will add something more to this topic?

About `AbstractQueryBuilderFilterImposer`. It has already a long name and I'm thinking about using namespaces for this. Like: `Doctrine\AbstractQueryBuilderFilterImposer`, so then we could create even `AbstractDBALFilterImposer` inside this namepsace - but I'm still not convinced if DBAL is necessary

**Comment by XanderEmu** [comment]
Using namespace sounds like a good idea ;]

**Comment by krzysztof-gzocha** [comment]
Would you like to send pull request about that? I mean to deprecate this one and create new imposer with "Doctrine" in namespace? If not I will do it tomorrow or day after
