### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by XanderEmu** [krzysztof-gzocha/searcher#17]
There is no usage example here. We can find one on Symfony Bundle page but Symfony integration shouldn't be more important than the library.

**Comment by krzysztof-gzocha** [comment]
Yes, you are right. Usage example is in presentation for this repo (http://krzysztof-gzocha.github.io/searcher), but I agree with you and I will put this example into README.md.

**Comment by krzysztof-gzocha** [comment]
Pull request #18 was merged, so I'm closing this issue. Thanks for your help, @XanderEmu
