### ISSUE TITLE
Add Doctrine SearchingContext adapter for enabling caching

### ISSUE THREAD

**Issue by krzysztof-gzocha** [krzysztof-gzocha/searcher#29]
# Idea
For now SearchingContexts are working pretty well, but if user wants to make use of Doctrine's caching mechanism then he needs to implement it on his own (which is not that hard). Target of this issue is to create an adapter/wrapper/anything that will make queriers inside SearchingContexts cacheable.

**Comment by medinae** [comment]
I'll analyze the issue and try to code a solution this week. @krzysztof-gzocha are you ok ?

**Comment by krzysztof-gzocha** [comment]
Yes, that's fine by me. If you will have any questions don't hesitate to ask them in here. Good luck

**Comment by medinae** [comment]
Do you want to use APC, Memcache, both of them ?

**Comment by krzysztof-gzocha** [comment]
It should be configurable by the user. User has to specify what to use, we just need to make it working with Searcher

**Comment by drgomesp** [comment]
What if I want to use Redis? As @krzysztof-gzocha, it should be tool-agnostic – exactly through an Adapter implementation. Maybe we can split the tasks, since should be able to have both Query Cache and Result Cache possibilities. Right now I'm more interested in Query Cache, since Result Cache can be implemented easily outside of searcher at the application level.

**Comment by medinae** [comment]
I'm ok to split the task, i think i will work on it this week end. For my part, i'm also interested by Query Cache but i'm ok to work on the **Result Cache**.

**Comment by krzysztof-gzocha** [comment]
I'm ok with splitting the task, but I have to agree with @drgomesp with:
> Right now I'm more interested in Query Cache, since Result Cache can be implemented easily outside of searcher at the application level.
Of course choice is yours and both cache mechanism will be appreciated.

**Comment by medinae** [comment]
Hi Krzysztof, i have no time to work on it this week end. Very sorry. Is there any deadline ?

**Comment by krzysztof-gzocha** [comment]
@medinae there is absolutely no problem. There is no deadline. I mean I hope that if somebody will start implementing this feature will let us know in this issue so our work will be a bit more coordinated :)

Right now I'm busy with migrating to version 3.0 in which names will be totally different, so if you want to implement this feature please start from branch `milestone-3.0` if version 3.0.0 will not be ready yet - I will add this info to issue description also.

Either way thanks for letting everyone knows - I really appreciate that :)

**Comment by medinae** [comment]
#87 Sorry for the delay... Just started my new job in Dubai and trying to find a flat and so on...
I will try to be more implicated now.

**Comment by krzysztof-gzocha** [comment]
Configuring query builders should be done outside of contexts. Done in #88
