### ISSUE TITLE
Rename things to make more sense

### ISSUE THREAD

**Issue by drgomesp** [krzysztof-gzocha/searcher#44]
I think Imposer and Model names are too generic. Maybe let's use Criteria and CriteriaBuilder?

Ex:

```php
interface SearchCriteriaInterface
{

}

class BedroomCriteria implements SearchCriteriaInterface
{
    public function getMin()
    {

    }

    public function getMax()
    {

    }
}

interface SearchCriteriaBuilderInterface
{
    public function build(SearchCriteriaInterface $criteria);
}

class BedroomCriteriaBuilder implements SearchCriteriaBuilderInterface
{
    /**
     * @var
     */
    protected $criteria;

    public function build(SearchCriteriaInterface $criteria)
    {
        $qb = $this->qb->where('bedroom', $criteria->getMin());
    }

    public function allowsCriteria(SearchCriteriaInterface $criteria)
    {
        return $criteria instanceof BedroomCriteria;
    }
}
```

**Comment by krzysztof-gzocha** [comment]
- I would change `allowsCriteria` to `supportsCriteria`, `build` to `buildCriteria`.
- How about `SearchingContext::getQueryBuilder` is it ok for you?
- `FilterModelCollection` would be changed to `CriteriaBuilderCollection` and `FilterModelCollection` to `CriteriaCollection`, right?
- Would you be able to code review eventual PR when this issue will be implemented, @drgomesp, or you want to implement this by your own?

**Comment by drgomesp** [comment]
> I would change allowsCriteria to supportsCriteria, build to buildCriteria.

That's good for me.

> How about SearchingContext::getQueryBuilder is it ok for you?

Yes, that makes more sense.

FilterModelCollection would be changed to CriteriaBuilderCollection and FilterModelCollection to CriteriaCollection, right?

Yes, and things are looking more clear now! 😄 

> Would you be able to code review eventual PR when this issue will be implemented, @drgomesp, or you want to implement this by your own?

Both options. I would prefer to actually implement it, but not sure when I'll have the time. Let's discuss it later.

**Comment by krzysztof-gzocha** [comment]
Ok, first PR to milestone 3.0.0 was merged #47. Now we need to document it properly. I'm closing this issue and documentation work can be done under issue #43. I'm starting working on branch `milestone-3.0`. Feel free to help

**Comment by barryvdh** [comment]
Sorry for the late reply,  but CriteriaBuilder seems a bit weird to me. You're not building any Criteria,  you are applying the Criteria to the QueryBuilder. Imho it now suggests that the CriteriaBuilder creates Criteria, which is obviously not the case. CriteriaApplier doesn't sound nice,. Buy something like CriteriaCompiler? As it compiles the Criteria into a query constraint.

**Comment by krzysztof-gzocha** [comment]
Hi.
Thanks for the feedback!

At first there was `ModelImposer`, but `Model` was changed to `Criteria` and `Imposer` into `Builder`. I agree that CriteriaApplier does not sound well. If you think of `compiling` as translating criteria into some abstract query, then maybe CriteriaCompiler would make sense, but what do you think about `CriteriaImposer` - wouldn't it be better?

//cc @drgomesp
