### ISSUE TITLE
Criteria constructors

### ISSUE THREAD

**Issue by barryvdh** [krzysztof-gzocha/searcher#73]
Is there a reason the default Criteria don't have a constructor to set the value?

The Complete example does have one and use it (`new HeightCriteria(200)`), which seems to make it more easy (instead of `(new HeightCriteria)->setHeight(200);`)

I can understand it might not be ideal for DI (with the Symfony bundle or something), but a default with null shouldn't hurt?

(Just checking if this is deliberate or not)

**Comment by krzysztof-gzocha** [comment]
No, there is no reason. All criteria can have constructor with proper values (default null).
I will mark this issue as an enhancement. 
Good idea! Thanks

**Comment by krzysztof-gzocha** [comment]
Hi, @barryvdh! Thanks for writing this issue. Today I had some time to add constructors to current ``Criteria``. It will be present in next minor version - which I will tag today (hopefully).

Kind regards
