### ISSUE TITLE
Implement and use CellCollection instead of an array in chain-searching

### ISSUE THREAD

**Issue by krzysztof-gzocha** [krzysztof-gzocha/searcher#90]
# Current implementation
Right now chain searching is requiring at least 2 cells to be provided as array to ChainSearch class and this class is responsible for validation of this array, but it should not care about it that much.

# Ideas
- Create `CellCollection` which will return cells only if all of it's elements are valid. Collection should extend `AbstractCollection` and should have it's own interface, which will extends `\Countable` and `\IteratorAggregate`
- Remove name from `CellInterface` and have `NamedCellCollection` which will extend regular `CellCollection` (with shared interface) just like we have it with `Criteria` for two thing: consistency and cell does not need to be aware of it's name, but name might be helpful to extract single cell from the collection (or to build service for some frameworks).

## Important
- Think if it's possible to keep backward compatibility
- Solution should be fully covered with unit tests
- Humbug's MSI factor should show 100%
- Scrutinizer's score should not be decreased

**Comment by medinae** [comment]
On me. I'll work on it this week end.

**Comment by krzysztof-gzocha** [comment]
I guess we should remove name from `CellInterface` and have `NamedCellCollection` just like we have it with `Criteria` for two thing: consistency and cell does not need to be aware of it's name, but name might be helpful to extract single cell from the collection (or to build service for some frameworks)

**Comment by krzysztof-gzocha** [comment]
@medinae in #94 there is my implementation of this issue. If you didn't started yet then I'd like to merge it to `master-4.0` and tag it as 4.0.0-alpha

**Comment by medinae** [comment]
I'll review that. Sorry guy, i was so busy those 2 weeks...
