### ISSUE TITLE
Add shared pre-build capabilities to CriteriaBuilders 

### ISSUE THREAD

**Issue by krzysztof-gzocha** [krzysztof-gzocha/searcher#98]
# Idea

In some cases it might be useful to create two separate CriteriaBuilders, that will share some common logic in order to build JOIN's for example. Even if the logic will be extracted to 3rd service it will still be run twice if both CriteriaBuilders will run.

Point of this issue would be to provide solution to somehow map what should be run before those CriteriaBuilders and if it was run before, do not allow to call it again.

In this way both CriteriaBuilders will be allowed to specify some service which will do JOINs, both can be called and logic that will actually add those JOINs will be called just once.
# Requirement

This can **NOT** break backward capabilities.
# Current work around

Current implementation is allowing developer to perform JOIN only if there is no such join in the Query, but this works only for Doctrine ORM. This code can be found in [AbstractORMCriteriaBuilder](https://github.com/krzysztof-gzocha/searcher/blob/master/src/KGzocha/Searcher/CriteriaBuilder/Doctrine/AbstractORMCriteriaBuilder.php), but it's not easy to use and will work only with Doctrine ORM. The code is as well marked as one of the worst methods in whole library according to [Scrutinizer CI](https://scrutinizer-ci.com/g/krzysztof-gzocha/searcher/code-structure/master/operation/KGzocha%5CSearcher%5CCriteriaBuilder%5CDoctrine%5CAbstractORMCriteriaBuilder%3A%3AfilterExistingJoins)
# Problem right now in pseudo-code

CriteriaBuilder1:

``` php
buildCriteria($criteria, $searchingContext)
{
   $searchingContext
      ->getQueryBuilder()
      ->join('p.user', 'u')          // this is the same
      ->where('u.name = :name')
      ->setParameter(':name', $criteria->getText());
}
```

CriteriaBuilder2:

``` php
buildCriteria($criteria, $searchingContext)
{
   $searchingContext
      ->getQueryBuilder()
      ->join('p.user', 'u')              // this is the same
      ->where('u.age = :age')     // this is changed
      ->setParameter(':age', $criteria->getNumber());
}
```

So now in current implementation if both CriteriaBuilders will be called then join will be added 2 times, which shouldn't happen. That's why there is `AbstractORMCriteriaBuilder::join`, so CriteriaBuilders can be changed and look like this:

CriteriaBuilder1:

``` php
// Needs to extend AbstractORMCriteriaBuilder
buildCriteria($criteria, $searchingContext)
{
   $this
      ->join($searchingContext->getQueryBuilder(), 'p.user', 'u', Join::INNER_JOIN)
      ->where('u.name = :name')
      ->setParameter(':name', $criteria->getText());
}
```

CriteriaBuilder2:

``` php
// Needs to extend AbstractORMCriteriaBuilder
buildCriteria($criteria, $searchingContext)
{
    $this
      ->join($searchingContext->getQueryBuilder(), 'p.user', 'u', Join::INNER_JOIN)
      ->where('u.age = :age')
      ->setParameter(':age', $criteria->getNumber());
}
```

Those joins can be for example moved to separate classes

**Comment by drgomesp** [comment]
What if we use some sort of composite pattern:

```php
interface SharedCriteriaSearchingContext extends SearchingContextInterface
{
    /**
     * @param $criteriaBuilder CriteriaBuilderInterface
     */
    public function applySharedCriteria(CriteriaBuilderInterface $criteriaBuilder); 
}

abstract class SharedJoinsQueryBuilderSearchingContext extends QueryBuilderSearchingContext implements SharedCriteriaSearchingContext
{
    public function getQueryBuilder()
    {
        $qb = parent::getQueryBuilder();
        $this->applySharedCriteria(&$qb);

        return $qb;
    }
}
```

**Comment by krzysztof-gzocha** [comment]
Hmm.. I like the idea, but it can not be applied at SearchingContext level, because some of the CriteriaBuilder's might not need the common logic and with this approach it would be still called even if not needed. I think we can achieve something similar but on CriteriaBuilders level.

**Comment by krzysztof-gzocha** [comment]
How about a decorator pattern?
There would be one decorator class and interface for "common logic".
We would inject both CriteriaBuilder and the common logic into the decorator.
There would be as many instances of decorator as many builders with shared logic there is, but only one instance of shared (common) logic, which would be triggered only once.

What do you think, @drgomesp?

**Comment by drgomesp** [comment]
@krzysztof-gzocha can you draft an example of that? I can't see it clearly yet...

**Comment by krzysztof-gzocha** [comment]
So we have `CriteriaBuilderWithJoin` that is doing some join (for example) and `AnotherCriteriaBuilderWithJoin` which needs exactly the same join, but it's building different conditions.

I was thinking about creating a decorator for `CriteriaBuilder` which would implement `CriteriaBuilderInterface`:
```php
class SharedPreBuilderCriteriaBuilderDecorator implements CriteriaBuilderInterface
{
    private $criteriaBuilder;
    private $sharedPreBuilder;

    public function __construct(
        CriteriaBuilderInterface $realCriteriaBuilder, 
        SharedPreBuilderInterface $preBuilder
    ) {
        $this->criteriaBuilder = $realCriteriaBuilder;
        $this->sharedPreBuilder = $preBuilder;
    }

    public function buildCriteria(
        CriteriaInterface $criteria,
        SearchingContextInterface $context
    ) {
        $this->sharedPreBuilder->build($criteria, $context);

        return $this->criteriaBuilder->buildCriteria($criteria, $context);
    }

    // allowsCriteria() and supportsSearchingContext() would be just a proxy to $this->criteriaBuilder
}
```

Above class will have it's own instance for each criteria builder.

After that we will create a `SharedPreBuilderInterface` (but only 1 instance) and we will inject it into both decorators:

```php
class SharedPreBuilder implements SharedPreBuilderInterface
{
    /** @var bool */
    private $wasCalled = false;

    public function build($criteria, $context)
    {
        if ($this->wasCalled) {
            return;
        }

        // In here we will perform the required joins
    }
}
```

So higher level logic would look like:
```php
$preBuilder = new SharedPreBuilder();

$builder1 = new SharedPreBuilderCriteriaBuilderDecorator(
    new CriteriaBuilderWithJoin(), 
    $preBuilder
);

$builder1 = new SharedPreBuilderCriteriaBuilderDecorator(
    new AnotherCriteriaBuilderWithJoin(), 
    $preBuilder
);

// Then we can just inject those builders into collection and later into Searcher class
// and act normally
```

Something like this, but of course naming would need to be improved

**Comment by krzysztof-gzocha** [comment]
I'm closing this issue as it won't improve readability of the code and will introduce only minor functionality.
